name: 'PHP Code Style (phpcs)'
description: 'PHPCS run'
author: 'David Lumaye (chindit)
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  dir:
    description: 'Folder to check code style'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
